version: '3'

services: 
  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    command: node index.js
    entrypoint: dockerize -wait tcp://db:3306 -timeout 15s docker-entrypoint.sh
    image: jessiiper/node
    container_name: node
    networks: 
      - nodenet
    volumes: 
      - ./node:/usr/src/app/api
    tty: true
    depends_on:
      - db
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: jessiiper/nginx
    container_name: nginx
    ports: 
      - "8080:80"
    networks: 
      - nodenet
    depends_on:
      - node
 
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

networks: 
  nodenet:
    name: nodenet
    driver: bridge